# Generated by Django 4.2.20 on 2025-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiaperChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("urine", models.BooleanField(default=False)),
                ("pooh", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PitStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("L", "Gauche"), ("R", "Droit")], max_length=1
                    ),
                ),
            ],
        ),
    ]
