# Generated by Django 4.2.20 on 2025-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agathe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitaminIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
