# Generated by Django 4.2 on 2025-02-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agathe", "0002_vitaminintake"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
