# Generated by Django 4.2.20 on 2025-08-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agathe', '0003_bath'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirinIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
