# Generated by Django 4.2.20 on 2025-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agathe', '0004_aspirinintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstop',
            name='delay_before_next_pit_stop',
            field=models.IntegerField(blank=True, help_text='in min', null=True),
        ),
    ]
