# Generated by Django 4.2.20 on 2025-09-25 19:45

from django.db import migrations, models


def delete_all_pit_stops(apps, schema_editor):
    PitStop = apps.get_model("agathe", "PitStop")
    PitStop.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agathe", "0005_pitstop_delay_before_next_pit_stop"),
    ]

    operations = [
        migrations.RunPython(delete_all_pit_stops, migrations.RunPython.noop),
        migrations.RemoveField(model_name="pitstop", name="end_date"),
        migrations.RemoveField(model_name="pitstop", name="side"),
        migrations.AddField(
            model_name="pitstop",
            name="quantity",
            field=models.IntegerField(default=0, help_text="in mL"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pitstop",
            name="comment",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
