# Generated by Django 4.2.20 on 2025-09-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agathe', '0006_pitstop_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AspirinIntake',
        ),
    ]
