# Generated by Django 4.2.20 on 2025-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='property_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
