# Generated by Django 4.2.20 on 2025-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance_simulator",
            "0002_simulation_monthly_expenses_simulation_property_tax",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="notary_fees",
            field=models.CharField(
                choices=[
                    ("no", "Non"),
                    ("new_property", "Neuf"),
                    ("old_property", "Ancien"),
                ],
                default="no",
                max_length=20,
            ),
        ),
    ]
