# Generated by Django 4.2.20 on 2025-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_simulator', '0003_simulation_notary_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='notary_fees',
            field=models.CharField(choices=[('NO', 'No'), ('NEW_PROPERTY', 'New Property'), ('OLD_PROPERTY', 'Old Property')], default='NO', max_length=20),
        ),
    ]
