# Generated by Django 4.2.20 on 2025-09-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_simulator', '0004_alter_simulation_notary_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='notary_fees',
            field=models.CharField(choices=[('NO', 'Absent'), ('NEW_PROPERTY', 'Neuf'), ('OLD_PROPERTY', 'Ancien')], default='NO', max_length=20),
        ),
    ]
