# Generated by Django 4.2.20 on 2025-04-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.family'),
        ),
    ]
