# Generated by Django 4.2.20 on 2025-10-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('job', models.CharField(choices=[('miner', 'Miner'), ('lumberjack', 'Lumberjack'), ('toolmaker', 'Tool Maker'), ('farmer', 'Farmer'), ('miller', 'Miller'), ('baker', 'Baker')], default='miner', max_length=32)),
                ('money', models.IntegerField(default=0)),
                ('time_since_need_fulfilled', models.IntegerField(default=0)),
                ('time_without_full_needs', models.IntegerField(default=0)),
                ('dead', models.BooleanField(default=False)),
                ('step', models.CharField(choices=[('start_of_day', 'Start of Day'), ('production', 'Production'), ('selling', 'Selling'), ('price_stats', 'Price Statistics'), ('buying', 'Buying'), ('consumption', 'Consumption'), ('death', 'Death'), ('analytics', 'Analytics'), ('end_of_day', 'End of Day')], default='start_of_day', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HumanAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('miner', 'Miner'), ('lumberjack', 'Lumberjack'), ('toolmaker', 'Tool Maker'), ('farmer', 'Farmer'), ('miller', 'Miller'), ('baker', 'Baker')], default='miner', max_length=32)),
                ('day_number', models.IntegerField(default=0)),
                ('number_alive', models.IntegerField(default=0)),
                ('average_money', models.FloatField(default=0.0)),
                ('lowest_money', models.IntegerField(default=0)),
                ('max_money', models.IntegerField(default=0)),
                ('new_joiner', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=0)),
                ('step', models.CharField(choices=[('start_of_day', 'Start of Day'), ('production', 'Production'), ('selling', 'Selling'), ('price_stats', 'Price Statistics'), ('buying', 'Buying'), ('consumption', 'Consumption'), ('death', 'Death'), ('analytics', 'Analytics'), ('end_of_day', 'End of Day')], default='start_of_day', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('ore', 'Ore'), ('wood', 'Wood'), ('wheat', 'Wheat'), ('flour', 'Flour'), ('bread', 'Bread'), ('pickaxe', 'Pickaxe'), ('axe', 'Axe'), ('scythe', 'Scythe'), ('spatula', 'Spatula')], max_length=32)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('object_type', models.CharField(choices=[('ore', 'Ore'), ('wood', 'Wood'), ('wheat', 'Wheat'), ('flour', 'Flour'), ('bread', 'Bread'), ('pickaxe', 'Pickaxe'), ('axe', 'Axe'), ('scythe', 'Scythe'), ('spatula', 'Spatula')], max_length=32)),
                ('lowest_price_displayed', models.IntegerField()),
                ('max_price_displayed', models.IntegerField()),
                ('average_price_displayed', models.FloatField()),
                ('lowest_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('average_price', models.FloatField()),
            ],
            options={
                'unique_together': {('day_number', 'object_type')},
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_sale', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('ore', 'Ore'), ('wood', 'Wood'), ('wheat', 'Wheat'), ('flour', 'Flour'), ('bread', 'Bread'), ('pickaxe', 'Pickaxe'), ('axe', 'Axe'), ('scythe', 'Scythe'), ('spatula', 'Spatula')], default='bread', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='capitalism.human')),
            ],
        ),
    ]
