# Generated by Django 4.2.20 on 2025-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
