# Generated by Django 4.2.20 on 2025-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0002_human_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='priceanalytics',
            name='lowest_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceanalytics',
            name='lowest_price_displayed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceanalytics',
            name='max_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceanalytics',
            name='max_price_displayed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(),
        ),
    ]
