# Generated by Django 4.2.20 on 2025-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0003_alter_object_price_alter_priceanalytics_lowest_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='money',
            field=models.IntegerField(default=150),
        ),
    ]
