# Generated by Django 4.2.20 on 2025-11-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0005_alter_human_money_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='humananalytics',
            name='dead_number',
            field=models.IntegerField(default=0),
        ),
    ]
