# Generated by Django 4.2.20 on 2025-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0008_priceanalytics_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPerceivedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.IntegerField()),
                ('perceived_price', models.FloatField()),
                ('object', models.CharField(choices=[('ore', 'Ore'), ('wood', 'Wood'), ('wheat', 'Wheat'), ('flour', 'Flour'), ('bread', 'Bread'), ('pickaxe', 'Pickaxe'), ('axe', 'Axe'), ('scythe', 'Scythe'), ('spatula', 'Spatula')], max_length=32)),
            ],
        ),
    ]
