# Generated by Django 4.2.20 on 2025-11-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0009_marketperceivedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketperceivedprice',
            name='object',
            field=models.CharField(choices=[('ore', 'Ore'), ('wood', 'Wood'), ('wheat', 'Wheat'), ('flour', 'Flour'), ('bread', 'Bread'), ('pickaxe', 'Pickaxe'), ('axe', 'Axe'), ('scythe', 'Scythe'), ('spatula', 'Spatula')], max_length=32, unique=True),
        ),
    ]
