# Generated by Django 4.2.20 on 2025-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0013_central_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='step',
            field=models.CharField(choices=[('start_of_day', 'Start of Day'), ('production', 'Production'), ('selling', 'Selling'), ('price_stats', 'Price Statistics'), ('buying', 'Buying'), ('consumption', 'Consumption'), ('death', 'Death'), ('analytics', 'Analytics'), ('government_actions', 'Government Actions'), ('end_of_day', 'End of Day')], default='start_of_day', max_length=32),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='step',
            field=models.CharField(choices=[('start_of_day', 'Start of Day'), ('production', 'Production'), ('selling', 'Selling'), ('price_stats', 'Price Statistics'), ('buying', 'Buying'), ('consumption', 'Consumption'), ('death', 'Death'), ('analytics', 'Analytics'), ('government_actions', 'Government Actions'), ('end_of_day', 'End of Day')], default='start_of_day', max_length=32),
        ),
    ]
