# Generated by Django 4.2.20 on 2025-12-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0014_alter_human_step_alter_simulation_step'),
        ('capitalism', '0014_central_government_default_money'),
    ]

    operations = [
    ]
