# Generated by Django 4.2.20 on 2025-12-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitalism', '0015_central_government_lifetime_collected_money'),
        ('capitalism', '0015_merge_20251228_1649'),
    ]

    operations = [
    ]
