# Generated by Django 4.2.20 on 2025-04-09 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BazaarRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('win_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('character', models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('VANESSA', 'Vanessa')], default='VANESSA', max_length=9)),
                ('archetype', models.CharField(choices=[('FIXER_UPPER', 'Fixer Upper')], max_length=11, null=True)),
                ('result', models.CharField(blank=True, choices=[('LOSS', 'Loss'), ('BRONZE_WIN', 'Bronze win'), ('SILVER_WIN', 'Silver win'), ('GOLD_WIN', 'Gold win')], max_length=10)),
            ],
        ),
    ]
