# Generated by Django 4.2.20 on 2025-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0004_alter_bazaarrun_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaarrun',
            name='archetype',
            field=models.CharField(blank=True, choices=[('FIXER_UPPER', 'Fixer Upper'), ('SINGLE_WEAPON', 'Single Weapon'), ('PUFFERFISH', 'Pufferfish'), ('LIGHTHOUSE_BURN', 'Lighthouse Burn'), ('DOUBLE_WHAMMY', 'Double Whammy'), ('POWER_DRILL', 'Power Drill'), ('SPIDER_MACE', 'Spider Mace'), ('BOTTLED_EXPLOSION', 'Bottled Explosion'), ('ACID_VAT', 'Vat of Acid'), ('STAFF_OF_THE_MOOSE', 'Staff of the Moose')], max_length=18, null=True),
        ),
    ]
