# Generated by Django 4.2.20 on 2025-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0007_bazaararchetype_bazaarrun_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaararchetype',
            name='is_meta_viable',
            field=models.BooleanField(default=True),
        ),
    ]
