# Generated by Django 4.2.20 on 2025-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0008_bazaararchetype_is_meta_viable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaarSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
            ],
        ),
    ]
