# Generated by Django 4.2.20 on 2025-04-11 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0010_bazaarrun_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaarseason',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20, validators=[django.core.validators.RegexValidator(message='Version must be of format X.Y.Z (typically, 1.0.0).', regex='^\\d+\\.\\d+\\.\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bazaarseason',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='bazaarseason',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
