# Generated by Django 4.2.20 on 2025-05-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0012_rename_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={},
        ),
    ]
