# Generated by Django 4.2.20 on 2025-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0013_alter_run_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
