# Generated by Django 4.2.20 on 2025-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0014_alter_season_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('character', models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('VANESSA', 'Vanessa')], max_length=9)),
                ('was_mastered', models.BooleanField(default=False)),
                ('victory_number', models.IntegerField()),
            ],
        ),
    ]
