# Generated by Django 4.2.20 on 2025-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0015_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='victory_number',
            field=models.IntegerField(default=0),
        ),
    ]
