# Generated by Django 4.2.20 on 2025-06-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0016_alter_object_victory_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "character",
                    models.CharField(
                        choices=[
                            ("DOOLEY", "Dooley"),
                            ("MAK", "Mak"),
                            ("PYGMALIEN", "Pygmalien"),
                            ("VANESSA", "Vanessa"),
                        ],
                        max_length=9,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="object",
            name="size",
            field=models.CharField(
                choices=[("SMALL", "Small"), ("MEDIUM", "Medium"), ("LARGE", "Large")],
                default="SMALL",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="card_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="the_bazaar.cardset",
            ),
        ),
    ]
