# Generated by Django 4.2.20 on 2025-06-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0017_cardset_object_size_object_card_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='character',
            field=models.CharField(blank=True, choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('VANESSA', 'Vanessa')], max_length=9, null=True),
        ),
    ]
