# Generated by Django 4.2.20 on 2025-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0018_alter_cardset_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="greenheart_dungeon",
            field=models.BooleanField(default=False),
        ),
    ]
