# Generated by Django 4.2.20 on 2025-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0019_add_greenheart_dungeon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], default='VANESSA', max_length=9),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='character',
            field=models.CharField(blank=True, choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], max_length=9),
        ),
        migrations.AlterField(
            model_name='run',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], default='VANESSA', max_length=9),
        ),
    ]
