# Generated by Django 4.2.20 on 2025-08-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0020_alter_archetype_character_alter_cardset_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='version',
        ),
    ]
