# Generated by Django 4.2.20 on 2025-08-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0021_remove_season_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='card_set',
        ),
        migrations.DeleteModel(
            name='CardSet',
        ),
    ]
