# Generated by Django 4.2.20 on 2025-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0022_remove_object_card_set_delete_cardset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], default='VANESSA', max_length=10),
        ),
    ]
