# Generated by Django 4.2.20 on 2025-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0024_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='is_victory',
            field=models.BooleanField(default=False),
        ),
    ]
