# Generated by Django 4.2.20 on 2025-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0026_fight_is_victory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa')], default='VANESSA', max_length=9),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
