# Generated by Django 4.2.20 on 2025-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0027_alter_archetype_character_alter_archetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], default='VANESSA', max_length=9),
        ),
        migrations.AlterField(
            model_name='fight',
            name='opponent_character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], max_length=9),
        ),
        migrations.AlterField(
            model_name='object',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], max_length=9),
        ),
        migrations.AlterField(
            model_name='run',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], default='VANESSA', max_length=9),
        ),
    ]
