# Generated by Django 4.2.20 on 2025-11-09 18:57

from django.db import migrations


def backfill_best_win(apps, schema_editor):
    Object = apps.get_model('the_bazaar', 'Object')
    for obj in Object.objects.all():
        if obj.gold_win_number > 0:
            best_win = 'GOLD_WIN'
        elif obj.silver_win_number > 0:
            best_win = 'SILVER_WIN'
        elif obj.bronze_win_number > 0:
            best_win = 'BRONZE_WIN'
        else:
            best_win = None
        if obj.best_win != best_win:
            obj.best_win = best_win
            obj.save(update_fields=['best_win'])


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0028_alter_archetype_character_and_more'),
    ]
    operations = [
        migrations.RunPython(backfill_best_win, migrations.RunPython.noop),
    ]
