# Generated by Django 4.2.20 on 2026-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0029_object_best_win_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='character',
            field=models.CharField(blank=True, choices=[('DOOLEY', 'Dooley'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], max_length=9, null=True),
        ),
    ]
