# Generated by Django 4.2.20 on 2026-02-05 00:00

from django.db import migrations, models


def create_dungeons(apps, schema_editor):
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")
    dungeon_model.objects.get_or_create(name="Greenheart Dungeon")
    dungeon_model.objects.get_or_create(name="Crash Site")


def delete_dungeons(apps, schema_editor):
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")
    dungeon_model.objects.filter(name__in=["Greenheart Dungeon", "Crash Site"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0030_alter_object_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dungeon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_dungeons, delete_dungeons),
    ]
