# Generated by Django 4.2.20 on 2026-02-05 00:00

from django.db import migrations, models


def add_greenheart_dungeon_to_runs(apps, schema_editor):
    run_model = apps.get_model("the_bazaar", "Run")
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")

    greenheart_dungeon, _ = dungeon_model.objects.get_or_create(name="Greenheart Dungeon")
    runs = run_model.objects.filter(greenheart_dungeon=True)
    for run in runs.iterator():
        run.dungeons.add(greenheart_dungeon)


def remove_greenheart_dungeon_from_runs(apps, schema_editor):
    run_model = apps.get_model("the_bazaar", "Run")
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")

    try:
        greenheart_dungeon = dungeon_model.objects.get(name="Greenheart Dungeon")
    except dungeon_model.DoesNotExist:
        return

    runs = run_model.objects.filter(greenheart_dungeon=True)
    for run in runs.iterator():
        run.dungeons.remove(greenheart_dungeon)


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0031_dungeon"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="dungeons",
            field=models.ManyToManyField(blank=True, to="the_bazaar.dungeon"),
        ),
        migrations.RunPython(
            add_greenheart_dungeon_to_runs,
            remove_greenheart_dungeon_from_runs,
        ),
    ]
