# Generated by Django 4.2.20 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0032_run_dungeons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="greenheart_dungeon",
        ),
    ]
