# Generated by Django 4.2.20 on 2026-02-05 00:00

from django.db import migrations, models


def set_dungeon_season_apparition(apps, schema_editor):
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")
    dungeon_model.objects.filter(name="Greenheart Dungeon").update(season_apparition=3)
    dungeon_model.objects.filter(name="Crash Site").update(season_apparition=7)


def unset_dungeon_season_apparition(apps, schema_editor):
    dungeon_model = apps.get_model("the_bazaar", "Dungeon")
    dungeon_model.objects.filter(name__in=["Greenheart Dungeon", "Crash Site"]).update(season_apparition=None)


class Migration(migrations.Migration):

    dependencies = [
        ("the_bazaar", "0033_remove_run_greenheart_dungeon"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeon",
            name="season_apparition",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_dungeon_season_apparition,
            unset_dungeon_season_apparition,
        ),
    ]
