# Generated by Django 4.2.20 on 2026-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_bazaar', '0034_dungeon_season_apparition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('KARNOK', 'Karnok'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], default='VANESSA', max_length=9),
        ),
        migrations.AlterField(
            model_name='fight',
            name='opponent_character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('KARNOK', 'Karnok'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], max_length=9),
        ),
        migrations.AlterField(
            model_name='object',
            name='character',
            field=models.CharField(blank=True, choices=[('DOOLEY', 'Dooley'), ('KARNOK', 'Karnok'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='character',
            field=models.CharField(choices=[('DOOLEY', 'Dooley'), ('KARNOK', 'Karnok'), ('MAK', 'Mak'), ('PYGMALIEN', 'Pygmalien'), ('STELLE', 'Stelle'), ('VANESSA', 'Vanessa'), ('JULES', 'Jules')], default='VANESSA', max_length=9),
        ),
    ]
