# Generated by Django 4.2.20 on 2025-07-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babyberon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "power",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Petite"), (2, "Moyenne"), (3, "Forte")]
                    ),
                ),
            ],
        ),
    ]
