# Generated by Django 4.2.20 on 2025-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyberon', '0002_contraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraction',
            name='power',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Strong')]),
        ),
    ]
