# Generated by Django 4.2.20 on 2025-04-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_course_name_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseelement',
            unique_together={('course', 'ingredient')},
        ),
    ]
