# Generated by Django 4.2.20 on 2025-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_alter_courseelement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, choices=[('DAIRY', 'Dairy'), ('FISH', 'Fish'), ('FRUIT', 'Fruit'), ('GRAINS', 'Grains'), ('MEAT', 'Meat'), ('NON_EDIBLE', 'Non Edible'), ('SPICE', 'Spice'), ('SWEET', 'Sweet'), ('VEGETABLE', 'Vegetable')], max_length=12, null=True),
        ),
    ]
