# Generated by Django 4.2.20 on 2025-04-13 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_coursehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehistory',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
