# Generated by Django 4.2.20 on 2025-05-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0007_alter_coursehistory_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={},
        ),
    ]
