# Generated by Django 4.2.20 on 2025-05-26 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0008_alter_shoppinglistitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_list.ingredient')),
            ],
        ),
    ]
