# Generated by Django 4.2.20 on 2025-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0009_ingredienthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienthistory',
            name='bought_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
