# Generated by Django 4.2.20 on 2025-07-13 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0010_alter_ingredienthistory_bought_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredienthistory",
            name="bought_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
