# Generated by Django 4.2.20 on 2026-04-26 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aodp_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('2H', '2H'), ('AGARIC', 'Agaric'), ('ALCHEMY', 'Alchemy'), ('ALCOHOL', 'Alcohol'), ('ARMOR', 'Armor'), ('ARTEFACT', 'Artefact'), ('BACKPACK', 'Backpack'), ('BAG', 'Bag'), ('BEAN', 'Bean'), ('BREAD', 'Bread'), ('BURDOCK', 'Burdock'), ('BUTTER', 'Butter'), ('CAPE', 'Cape'), ('CAPEITEM', 'Cape Item'), ('CABBAGE', 'Cabbage'), ('CARROT', 'Carrot'), ('CLOTH', 'Cloth'), ('COMFREY', 'Comfrey'), ('CORN', 'Corn'), ('CORRUPTED', 'Corrupted'), ('EGG', 'Egg'), ('ESSENCE', 'Essence'), ('FACTION', 'Faction'), ('FARM', 'Farm'), ('FIBER', 'Fiber'), ('FISH', 'Fish'), ('FISHCHOPS', 'Fish Chops'), ('FISHINGBAIT', 'Fishing Bait'), ('FISHSAUCE', 'Fish Sauce'), ('FLOUR', 'Flour'), ('FOCUSPOTION', 'Focus Potion'), ('FOXGLOVE', 'Foxglove'), ('FURNITUREITEM', 'Furniture Item'), ('GENERAL', 'General'), ('GVGSEASONREWARD', 'GvG Season Reward'), ('HEAD', 'Head'), ('HELLGATE', 'Hellgate'), ('HIDE', 'Hide'), ('JOURNAL', 'Journal'), ('KILL', 'Kill'), ('LABOURER', 'Labourer'), ('LEARNINGPOINTS', 'Learning Points'), ('LEATHER', 'Leather'), ('LOOTBAG', 'Loot Bag'), ('LOOTCHEST', 'Loot Chest'), ('MAIN', 'Main'), ('MEAL', 'Meal'), ('MEAT', 'Meat'), ('METALBAR', 'Metal Bar'), ('MILK', 'Milk'), ('MOUNT', 'Mount'), ('MOUNTUPGRADE', 'Mount Upgrade'), ('MULLEIN', 'Mullein'), ('OFF', 'Off Hand'), ('ORE', 'Ore'), ('PLANKS', 'Planks'), ('PLAYERISLAND', 'Player Island'), ('POTATO', 'Potato'), ('POTION', 'Potion'), ('PREMIUMITEM', 'Premium Item'), ('PUMPKIN', 'Pumpkin'), ('QUESTITEM', 'Quest Item'), ('RANDOM', 'Random'), ('RELIC', 'Relic'), ('ROCK', 'Rock'), ('RUNE', 'Rune'), ('SEAWEED', 'Seaweed'), ('SHARD', 'Shard'), ('SHOES', 'Shoes'), ('SIEGE', 'Siege'), ('SILVERBAG', 'Silver Bag'), ('SKILLBOOK', 'Skill Book'), ('SKIN', 'Skin'), ('SOUL', 'Soul'), ('STONEBLOCK', 'Stone Block'), ('TEASEL', 'Teasel'), ('TREASURE', 'Treasure'), ('TRASH', 'Trash'), ('TURNIP', 'Turnip'), ('UNIQUE', 'Unique'), ('VANITY', 'Vanity'), ('WHEAT', 'Wheat'), ('WOOD', 'Wood'), ('WORM', 'Worm'), ('YARROW', 'Yarrow')], db_index=True, max_length=32)),
                ('tier', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('enchantment', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'ordering': ('type', 'tier', 'enchantment', 'aodp_id'),
            },
        ),
    ]
