# Generated by Django 4.2.20 on 2026-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0002_import_objects_from_aodp_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.CharField(choices=[('2H', '2H'), ('AGARIC', 'Agaric'), ('ALCHEMY', 'Alchemy'), ('ALCOHOL', 'Alcohol'), ('ARMOR', 'Armor'), ('ARTEFACT', 'Artefact'), ('BACKPACK', 'Backpack'), ('BAG', 'Bag'), ('BEAN', 'Bean'), ('BREAD', 'Bread'), ('BURDOCK', 'Burdock'), ('BUTTER', 'Butter'), ('CAPE', 'Cape'), ('CAPEITEM', 'Cape Item'), ('CABBAGE', 'Cabbage'), ('CARROT', 'Carrot'), ('CLOTH', 'Cloth'), ('COMFREY', 'Comfrey'), ('CONSUMABLE', 'Consumable'), ('CORN', 'Corn'), ('CORRUPTED', 'Corrupted'), ('EGG', 'Egg'), ('ESSENCE', 'Essence'), ('FACTION', 'Faction'), ('FARM', 'Farm'), ('FIBER', 'Fiber'), ('FISH', 'Fish'), ('FISHCHOPS', 'Fish Chops'), ('FISHINGBAIT', 'Fishing Bait'), ('FISHSAUCE', 'Fish Sauce'), ('FLOUR', 'Flour'), ('FOCUSPOTION', 'Focus Potion'), ('FOXGLOVE', 'Foxglove'), ('FURNITUREITEM', 'Furniture Item'), ('GENERAL', 'General'), ('GVGSEASONREWARD', 'GvG Season Reward'), ('HEAD', 'Head'), ('HELLGATE', 'Hellgate'), ('HIDE', 'Hide'), ('JOURNAL', 'Journal'), ('KILL', 'Kill'), ('LABOURER', 'Labourer'), ('LEARNINGPOINTS', 'Learning Points'), ('LEATHER', 'Leather'), ('LOOTBAG', 'Loot Bag'), ('LOOTCHEST', 'Loot Chest'), ('MAIN', 'Main'), ('MEAL', 'Meal'), ('MEAT', 'Meat'), ('METALBAR', 'Metal Bar'), ('MILK', 'Milk'), ('MOUNT', 'Mount'), ('MOUNTUPGRADE', 'Mount Upgrade'), ('MULLEIN', 'Mullein'), ('OFF', 'Off Hand'), ('ORE', 'Ore'), ('PLANKS', 'Planks'), ('PLAYERISLAND', 'Player Island'), ('POTATO', 'Potato'), ('POTION', 'Potion'), ('PREMIUMITEM', 'Premium Item'), ('PUMPKIN', 'Pumpkin'), ('QUESTITEM', 'Quest Item'), ('RANDOM', 'Random'), ('RELIC', 'Relic'), ('ROCK', 'Rock'), ('RUNE', 'Rune'), ('SEAWEED', 'Seaweed'), ('SHARD', 'Shard'), ('SHOES', 'Shoes'), ('SIEGE', 'Siege'), ('SILVERBAG', 'Silver Bag'), ('SKILLBOOK', 'Skill Book'), ('SKIN', 'Skin'), ('SOUL', 'Soul'), ('STONEBLOCK', 'Stone Block'), ('TEASEL', 'Teasel'), ('TREASURE', 'Treasure'), ('TRASH', 'Trash'), ('TURNIP', 'Turnip'), ('UNIQUE', 'Unique'), ('VANITY', 'Vanity'), ('WHEAT', 'Wheat'), ('WOOD', 'Wood'), ('WORM', 'Worm'), ('YARROW', 'Yarrow')], db_index=True, max_length=32),
        ),
    ]
