# Generated by Django 4.2.20 on 2026-04-26 20:01

from django.db import migrations, models


EQUIPMENT_CATEGORIES_BY_TYPE = {
    "ARMOR": "CHEST",
    "OFF": "OFFHAND",
    "MAIN": "SINGLE_HAND",
    "2H": "TWO_HAND",
    "SHOES": "BOOT",
}


def backfill_equipment_category(apps, schema_editor):
    Object = apps.get_model("albion_online", "Object")
    for object_type, equipment_category in EQUIPMENT_CATEGORIES_BY_TYPE.items():
        Object.objects.filter(type=object_type).update(
            equipment_category=equipment_category
        )


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0003_alter_object_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('equipment_category', 'type', 'tier', 'enchantment', 'aodp_id')},
        ),
        migrations.AddField(
            model_name='object',
            name='equipment_category',
            field=models.CharField(blank=True, choices=[('CHEST', 'Chest'), ('OFFHAND', 'Offhand'), ('SINGLE_HAND', 'Single Hand'), ('TWO_HAND', 'Two-Hand'), ('BOOT', 'Boot')], db_index=True, max_length=16, null=True),
        ),
        migrations.RunPython(backfill_equipment_category, migrations.RunPython.noop),
    ]
