# Generated by Django 4.2.20 on 2026-04-26 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0006_backfill_crafting_tree_and_rename_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('city', models.CharField(choices=[('BRIDGEWATCH', 'Bridgewatch'), ('CAERLEON', 'Caerleon'), ('FORT_STERLING', 'Fort Sterling'), ('LYMHURST', 'Lymhurst'), ('MARTLOCK', 'Martlock'), ('THETFORD', 'Thetford'), ('BRECIEN', 'Brecien')], db_index=True, max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('quality', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='albion_online.object')),
            ],
            options={
                'ordering': ('-timestamp', 'city', 'object_id', 'quality'),
                'indexes': [models.Index(fields=['object', 'city', 'quality', '-timestamp'], name='albion_onli_object__86ee81_idx')],
            },
        ),
    ]
