# Generated by Django 4.2.20 on 2026-04-26 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def build_tier_enchantment_notation(tier, enchantment):
    if tier is None:
        return None
    return f"{tier}.{enchantment}"


def backfill_tier_enchantment_notation(apps, schema_editor):
    Object = apps.get_model("albion_online", "Object")
    objects_to_update = []
    for albion_object in Object.objects.all().only(
        "id",
        "tier",
        "enchantment",
        "tier_enchantment_notation",
    ):
        notation = build_tier_enchantment_notation(
            albion_object.tier,
            albion_object.enchantment,
        )
        if albion_object.tier_enchantment_notation != notation:
            albion_object.tier_enchantment_notation = notation
            objects_to_update.append(albion_object)

    Object.objects.bulk_update(
        objects_to_update,
        ["tier_enchantment_notation"],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0007_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('output__crafting_tree', 'output__tier', 'output__enchantment', 'output__aodp_id'),
            },
        ),
        migrations.AddField(
            model_name='object',
            name='tier_enchantment_notation',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.RunPython(
            backfill_tier_enchantment_notation,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_inputs', to='albion_online.object')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='albion_online.recipe')),
            ],
            options={
                'ordering': ('recipe_id', 'object__type', 'object__aodp_id'),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_recipes', to='albion_online.object'),
        ),
        migrations.AddConstraint(
            model_name='recipeinput',
            constraint=models.UniqueConstraint(fields=('recipe', 'object'), name='albion_unique_recipe_input_object'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('output',), name='albion_unique_recipe_output'),
        ),
    ]
