# Generated by Django 4.2.20 on 2026-04-26 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0008_recipe_object_tier_enchantment_notation_recipeinput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='quality',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
