# Generated by Django 4.2.20 on 2026-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0009_alter_price_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='city',
            field=models.CharField(choices=[('BRIDGEWATCH', 'Bridgewatch'), ('CAERLEON', 'Caerleon'), ('FORT_STERLING', 'Fort Sterling'), ('LYMHURST', 'Lymhurst'), ('MARTLOCK', 'Martlock'), ('THETFORD', 'Thetford'), ('BRECILIEN', 'Brecilien')], db_index=True, max_length=16),
        ),
    ]
