# Generated by hand to avoid interactive rename prompts.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0010_alter_price_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="price",
            new_name="sell_price_min",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="timestamp",
            new_name="sell_price_min_date",
        ),
        migrations.AddField(
            model_name="price",
            name="sell_price_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="sell_price_max_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="buy_price_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="buy_price_min_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="buy_price_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="buy_price_max_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveIndex(
            model_name="price",
            name="albion_onli_object__86ee81_idx",
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["object", "city", "quality", "-sell_price_min_date"],
                name="albion_onli_object__be6e18_idx",
            ),
        ),
        migrations.AlterModelOptions(
            name="price",
            options={
                "ordering": ("-sell_price_min_date", "city", "object_id", "quality"),
            },
        ),
    ]
