# Generated by Django 4.2.20 on 2026-04-27 16:07

from django.db import migrations, models
import django.db.models.deletion


def create_initial_recipe_definitions(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")
    RecipeDefinition.objects.update_or_create(
        key="mercenary_jacket",
        defaults={
            "name": "Mercenary Jacket recipes",
            "config": {
                "output_filter": {
                    "aodp_id__contains": "ARMOR_LEATHER_SET1",
                    "type": "ARMOR",
                    "equipment_category": "CHEST",
                    "crafting_tree": "leather_chest",
                    "tier__gte": 4,
                },
                "output_quantity": 1,
                "inputs": [
                    {
                        "object_filter": {
                            "type": "LEATHER",
                        },
                        "tier_mode": "same_as_output",
                        "enchantment_mode": "same_as_output",
                        "quantity": 16,
                    }
                ],
            },
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0011_price_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='albion_online.recipedefinition'),
        ),
        migrations.RunPython(create_initial_recipe_definitions, migrations.RunPython.noop),
    ]
