# Generated by Codex on 2026-04-27

from django.db import migrations


def add_resource_return_rate_to_mercenary_jacket_definition(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")
    recipe_definition = RecipeDefinition.objects.filter(key="mercenary_jacket").first()
    if recipe_definition is None:
        return

    config = dict(recipe_definition.config or {})
    resource_return_rate = dict(config.get("resource_return_rate") or {})
    resource_return_rate.setdefault("default", 0.153)
    resource_return_rate.setdefault("city_overrides", {})
    config["resource_return_rate"] = resource_return_rate
    recipe_definition.config = config
    recipe_definition.save(update_fields=["config"])


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0012_recipedefinition_and_more"),
    ]

    operations = [
        migrations.RunPython(add_resource_return_rate_to_mercenary_jacket_definition, migrations.RunPython.noop),
    ]
