# Generated by Codex on 2026-04-27

from django.db import migrations
from django.db import models


def move_resource_return_rate_to_objects(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")

    for recipe_definition in RecipeDefinition.objects.all():
        config = dict(recipe_definition.config or {})
        resource_return_rate_config = config.pop("resource_return_rate", None)
        if resource_return_rate_config is not None:
            recipe_definition.config = config
            recipe_definition.save(update_fields=["config"])

        if resource_return_rate_config is None:
            continue

        for recipe in recipe_definition.recipes.select_related("output").all():
            output_object = recipe.output
            if output_object.resource_return_rate_config:
                continue

            output_object.resource_return_rate_config = resource_return_rate_config
            output_object.save(update_fields=["resource_return_rate_config"])


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0013_recipe_definition_resource_return_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="resource_return_rate_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(move_resource_return_rate_to_objects, migrations.RunPython.noop),
    ]
