# Generated by Codex on 2026-04-27

from django.db import migrations, models

from albion_online.constants.city import City


def move_resource_return_rate_city_to_object(apps, schema_editor):
    Object = apps.get_model("albion_online", "Object")

    for output_object in Object.objects.all():
        resource_return_rate_config = output_object.resource_return_rate_config or {}
        if not isinstance(resource_return_rate_config, dict):
            continue

        city_overrides = resource_return_rate_config.get("city_overrides", {})
        if not isinstance(city_overrides, dict) or not city_overrides:
            continue

        specialized_city = next(iter(city_overrides.keys()))
        output_object.resource_return_rate_city = specialized_city
        output_object.save(update_fields=["resource_return_rate_city"])


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0014_object_resource_return_rate_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="resource_return_rate_city",
            field=models.CharField(blank=True, choices=City.choices, db_index=True, max_length=16, null=True),
        ),
        migrations.RunPython(move_resource_return_rate_city_to_object, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="object",
            name="resource_return_rate_config",
        ),
    ]
