# Generated by Codex on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion

from albion_online.constants.object_type import ObjectType


def create_object_type_groups(apps, schema_editor):
    Object = apps.get_model("albion_online", "Object")
    ObjectTypeGroup = apps.get_model("albion_online", "ObjectTypeGroup")

    existing_type_codes = set(Object.objects.values_list("type", flat=True).distinct())
    known_labels = {code: label for code, label in ObjectType.choices}
    for code in sorted(existing_type_codes.union(known_labels.keys())):
        ObjectTypeGroup.objects.update_or_create(
            code=code,
            defaults={"name": known_labels.get(code, code.replace("_", " ").title())},
        )


def move_resource_return_rate_to_object_type_groups(apps, schema_editor):
    Object = apps.get_model("albion_online", "Object")
    ObjectTypeGroup = apps.get_model("albion_online", "ObjectTypeGroup")

    for object_type_group in ObjectTypeGroup.objects.all():
        specialized_cities = (
            Object.objects.filter(type=object_type_group, resource_return_rate_city__isnull=False)
            .values_list("resource_return_rate_city", flat=True)
            .distinct()
        )
        specialized_cities = list(specialized_cities)
        if not specialized_cities:
            continue
        if len(specialized_cities) > 1:
            raise ValueError(
                f"Multiple resource return cities found for object type {object_type_group.code}: {specialized_cities}"
            )
        object_type_group.resource_return_rate_city = specialized_cities[0]
        object_type_group.save(update_fields=["resource_return_rate_city"])


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0015_object_resource_return_rate_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectTypeGroup",
            fields=[
                ("code", models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "resource_return_rate_city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BRIDGEWATCH", "Bridgewatch"),
                            ("CAERLEON", "Caerleon"),
                            ("FORT_STERLING", "Fort Sterling"),
                            ("LYMHURST", "Lymhurst"),
                            ("MARTLOCK", "Martlock"),
                            ("THETFORD", "Thetford"),
                            ("BRECILIEN", "Brecilien"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.RunPython(create_object_type_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="object",
            name="type",
            field=models.ForeignKey(
                db_column="type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="typed_objects",
                to="albion_online.objecttypegroup",
                to_field="code",
            ),
        ),
        migrations.RunPython(move_resource_return_rate_to_object_type_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="object",
            name="resource_return_rate_city",
        ),
    ]
