# Generated by Codex on 2026-04-29

from django.db import migrations


def build_leather_jacket_config(aodp_id_fragment):
    return {
        "output_filter": {
            "aodp_id__contains": aodp_id_fragment,
            "type": "ARMOR",
            "equipment_category": "CHEST",
            "crafting_tree": "leather_chest",
            "tier__gte": 4,
        },
        "output_quantity": 1,
        "inputs": [
            {
                "object_filter": {
                    "type": "LEATHER",
                },
                "tier_mode": "same_as_output",
                "enchantment_mode": "same_as_output",
                "quantity": 16,
            }
        ],
    }


def add_jacket_recipe_definitions(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")
    definitions = (
        ("hunter_jacket", "Hunter Jacket recipes", "ARMOR_LEATHER_SET2"),
        ("assassin_jacket", "Assassin Jacket recipes", "ARMOR_LEATHER_SET3"),
    )
    for key, name, aodp_id_fragment in definitions:
        RecipeDefinition.objects.update_or_create(
            key=key,
            defaults={
                "name": name,
                "config": build_leather_jacket_config(aodp_id_fragment),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0016_object_type_group_and_object_type_fk"),
    ]

    operations = [
        migrations.RunPython(add_jacket_recipe_definitions, migrations.RunPython.noop),
    ]
