# Generated by Django 4.2.20 on 2026-04-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0017_add_hunter_assassin_jacket_recipe_definitions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='price',
            new_name='albion_onli_object__ab8277_idx',
            old_name='albion_onli_object__be6e18_idx',
        ),
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, related_name='typed_objects', to='albion_online.objecttypegroup'),
        ),
    ]
