# Generated by Codex on 2026-05-08

from django.db import migrations


def build_stalker_jacket_config():
    return {
        "output_filter": {
            "aodp_id__contains": "ARMOR_LEATHER_MORGANA",
            "type": "ARMOR",
            "equipment_category": "CHEST",
            "crafting_tree": "leather_chest",
            "tier__gte": 4,
        },
        "output_quantity": 1,
        "inputs": [
            {
                "object_filter": {
                    "type": "LEATHER",
                },
                "tier_mode": "same_as_output",
                "enchantment_mode": "same_as_output",
                "quantity": 16,
            },
            {
                "object_filter": {
                    "aodp_id__contains": "ARTEFACT_ARMOR_LEATHER_MORGANA",
                    "type": "ARTEFACT",
                },
                "tier_mode": "same_as_output",
                "enchantment_mode": "none",
                "quantity": 1,
            },
        ],
    }


def add_stalker_jacket_recipe_definition(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")
    RecipeDefinition.objects.update_or_create(
        key="stalker_jacket",
        defaults={
            "name": "Stalker Jacket recipes",
            "config": build_stalker_jacket_config(),
            "is_active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0018_rename_albion_onli_object__be6e18_idx_albion_onli_object__ab8277_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(add_stalker_jacket_recipe_definition, migrations.RunPython.noop),
    ]
