# Generated by Codex on 2026-05-08

from django.db import migrations


def build_artifact_jacket_config(output_fragment, artifact_fragment, leather_quantity):
    return {
        "output_filter": {
            "aodp_id__contains": output_fragment,
            "type": "ARMOR",
            "equipment_category": "CHEST",
            "crafting_tree": "leather_chest",
            "tier__gte": 4,
        },
        "output_quantity": 1,
        "inputs": [
            {
                "object_filter": {
                    "type": "LEATHER",
                },
                "tier_mode": "same_as_output",
                "enchantment_mode": "same_as_output",
                "quantity": leather_quantity,
            },
            {
                "object_filter": {
                    "aodp_id__contains": artifact_fragment,
                    "type": "ARTEFACT",
                },
                "tier_mode": "same_as_output",
                "enchantment_mode": "none",
                "quantity": 1,
            },
        ],
    }


def add_artifact_leather_jacket_recipe_definitions(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")
    definitions = (
        (
            "hellion_jacket",
            "Hellion Jacket recipes",
            "ARMOR_LEATHER_HELL",
            "ARTEFACT_ARMOR_LEATHER_HELL",
            16,
        ),
        (
            "specter_jacket",
            "Specter Jacket recipes",
            "ARMOR_LEATHER_UNDEAD",
            "ARTEFACT_ARMOR_LEATHER_UNDEAD",
            16,
        ),
        (
            "tenacity_jacket",
            "Jacket of Tenacity recipes",
            "ARMOR_LEATHER_AVALON",
            "ARTEFACT_ARMOR_LEATHER_AVALON",
            16,
        ),
        (
            "mistwalker_jacket",
            "Mistwalker Jacket recipes",
            "ARMOR_LEATHER_FEY",
            "ARTEFACT_ARMOR_LEATHER_FEY",
            8,
        ),
    )
    for key, name, output_fragment, artifact_fragment, leather_quantity in definitions:
        RecipeDefinition.objects.update_or_create(
            key=key,
            defaults={
                "name": name,
                "config": build_artifact_jacket_config(output_fragment, artifact_fragment, leather_quantity),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0019_add_stalker_jacket_recipe_definition"),
    ]

    operations = [
        migrations.RunPython(add_artifact_leather_jacket_recipe_definitions, migrations.RunPython.noop),
    ]
