# Generated by Codex on 2026-05-14

from copy import deepcopy

from django.db import migrations

from albion_online.constants.gathering_gear import GATHERING_GEAR_RECIPE_DEFINITIONS


def add_gathering_gear_recipe_definitions(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")

    for recipe_definition in GATHERING_GEAR_RECIPE_DEFINITIONS:
        RecipeDefinition.objects.update_or_create(
            key=recipe_definition["key"],
            defaults={
                "name": recipe_definition["name"],
                "config": deepcopy(recipe_definition["config"]),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0020_add_artifact_leather_jacket_recipe_definitions"),
    ]

    operations = [
        migrations.RunPython(add_gathering_gear_recipe_definitions, migrations.RunPython.noop),
    ]
