# Generated by Django 4.2.20 on 2026-05-14 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0021_add_gathering_gear_recipe_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatheringGearProfitabilityDoneCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('BRIDGEWATCH', 'Bridgewatch'), ('CAERLEON', 'Caerleon'), ('FORT_STERLING', 'Fort Sterling'), ('LYMHURST', 'Lymhurst'), ('MARTLOCK', 'Martlock'), ('THETFORD', 'Thetford'), ('BRECILIEN', 'Brecilien')], db_index=True, max_length=16)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_gear_profitability_done_crafts', to='albion_online.object')),
            ],
            options={
                'ordering': ('-completed_at', 'city', 'object'),
            },
        ),
        migrations.AddConstraint(
            model_name='gatheringgearprofitabilitydonecraft',
            constraint=models.UniqueConstraint(fields=('object', 'city'), name='albion_unique_gathering_gear_profitability_done_craft'),
        ),
    ]
