# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("albion_online", "0022_gatheringgearprofitabilitydonecraft_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GatheringGearProfitabilityDoneCraft",
            new_name="CraftProfitabilityDone",
        ),
        migrations.AlterField(
            model_name="craftprofitabilitydone",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="craft_profitability_done_records",
                to="albion_online.object",
            ),
        ),
    ]
