# Generated by Codex on 2026-05-14

from copy import deepcopy

from django.db import migrations


GARB_RECIPE_KEYS = {
    "miner_chest",
    "harvester_chest",
    "lumberjack_chest",
    "quarrier_chest",
    "skinner_chest",
}


def fix_gathering_gear_garb_recipe_input_quantity(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")

    for recipe_definition in RecipeDefinition.objects.filter(key__in=GARB_RECIPE_KEYS):
        config = deepcopy(recipe_definition.config)
        inputs = config.get("inputs", [])
        if not inputs:
            continue
        inputs[0]["quantity"] = 16
        recipe_definition.config = config
        recipe_definition.save(update_fields=["config"])


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0023_craftprofitabilitydone_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_gathering_gear_garb_recipe_input_quantity, migrations.RunPython.noop),
    ]
