# Generated by Codex on 2026-05-15

from copy import deepcopy

from django.db import migrations


def rename_gathering_gear_stone_to_rock(apps, schema_editor):
    RecipeDefinition = apps.get_model("albion_online", "RecipeDefinition")

    recipe_definition = RecipeDefinition.objects.filter(key="stone").first()
    if recipe_definition is None:
        recipe_definition = RecipeDefinition.objects.filter(key="rock").first()
    if recipe_definition is None:
        return

    config = deepcopy(recipe_definition.config or {})
    output_filter = config.get("output_filter", {})
    crafting_tree = output_filter.get("crafting_tree")
    if isinstance(crafting_tree, str):
        output_filter["crafting_tree"] = crafting_tree.replace("gatherer_stone_", "gatherer_rock_")
    config["output_filter"] = output_filter

    recipe_definition.config = config
    if recipe_definition.key == "stone":
        recipe_definition.key = "rock"
    recipe_definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0025_fix_gathering_gear_garb_recipe_input_quantity"),
    ]

    operations = [
        migrations.RunPython(rename_gathering_gear_stone_to_rock, migrations.RunPython.noop),
    ]
