# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albion_online", "0026_rename_gathering_gear_stone_to_rock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRefreshJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("leather_jacket", "Leather jacket"),
                            ("gathering_gear", "Gathering gear"),
                            ("artifact_salvage", "Artifact salvage"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("running", "Running"), ("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("refreshed_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
    ]
