# Generated by Django 4.2.30 on 2026-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albion_online', '0027_price_refresh_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AodpRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('request_url', models.TextField()),
                ('request_query_string', models.TextField(blank=True)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('response_body_raw', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['created_at'], name='albion_onli_created_5d403e_idx'), models.Index(fields=['source', 'created_at'], name='albion_onli_source_283af8_idx'), models.Index(fields=['is_error', 'created_at'], name='albion_onli_is_erro_4db929_idx')],
            },
        ),
    ]
