# Generated by Django 4.2.20 on 2025-11-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_answer', models.DateTimeField(blank=True, null=True)),
                ('answer_number', models.PositiveIntegerField(default=0)),
                ('last_answer_result', models.BooleanField(default=False)),
                ('positive_answer_number', models.PositiveIntegerField(default=0)),
                ('negative_answer_number', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flash_cards.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
