# Generated by Django 4.2.20 on 2025-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0005_alter_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='theme_presets', to='flash_cards.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
