# Generated by Django 4.2.20 on 2025-11-21 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_cards', '0006_themepreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer', models.DateTimeField(blank=True, null=True)),
                ('answer_number', models.PositiveIntegerField(default=0)),
                ('last_answer_result', models.BooleanField(default=False)),
                ('positive_answer_number', models.PositiveIntegerField(default=0)),
                ('negative_answer_number', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='flash_cards.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'question'),
                'unique_together': {('user', 'question')},
            },
        ),
    ]
