# Generated by Django 4.2.20 on 2025-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_cards", "0007_questionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="needs_rework",
            field=models.BooleanField(default=False),
        ),
    ]
