# Generated by Django 4.2.20 on 2025-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_name', '0005_alter_evaluation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='source',
            field=models.CharField(default='Ile de France', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
