# Generated by Django 4.2.20 on 2025-04-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_name', '0006_name_source_name_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='name',
            unique_together={('name', 'sex')},
        ),
    ]
