# Generated by Django 4.2.20 on 2025-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='game',
            field=models.CharField(blank=True, choices=[('bttd', 'Back to the Dawn')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
