# Generated by Django 4.2.20 on 2025-08-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_game_alter_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='game',
            new_name='directory',
        ),
    ]
