# Generated by Django 4.2.20 on 2025-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_game_document_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='directory',
            field=models.CharField(blank=True, choices=[('bttd', 'Back to the Dawn'), ('civilization_7', 'Civilization 7'), ('altered', 'Altered'), ('runeterra', 'Runeterra'), ('bazaar', 'The Bazaar')], max_length=14, null=True),
        ),
    ]
