# Generated by Django 4.2.20 on 2025-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='directory',
            field=models.CharField(blank=True, choices=[('agathe', 'Agathe'), ('altered', 'Altered'), ('bttd', 'Back to the Dawn'), ('bazaar', 'The Bazaar'), ('civilization_7', 'Civilization 7'), ('finance', 'Finance Simulator'), ('runeterra', 'Runeterra')], max_length=14, null=True),
        ),
    ]
