# Generated by Django 4.2.20 on 2025-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='directory',
            field=models.CharField(blank=True, choices=[('agathe', 'Agathe'), ('altered', 'Altered'), ('bttd', 'Back to the Dawn'), ('bazaar', 'The Bazaar'), ('civilization_7', 'Civilization 7'), ('finance', 'Finance Simulator'), ('capitalism', 'Capitalism'), ('silksong', 'Silksong'), ('runeterra', 'Runeterra'), ('speedrun', 'Speedrun'), ('sport', 'Sport')], max_length=14, null=True),
        ),
    ]
