# Generated by Django 4.2.20 on 2025-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('faction', models.CharField(choices=[('AXIOM', 'Axiom'), ('BRAVOS', 'Bravos'), ('LYRA', 'Lyra'), ('MUNA', 'Muna'), ('ORDIS', 'Ordis'), ('YZMIR', 'Yzmir')], max_length=8)),
            ],
        ),
    ]
