# Generated by Django 4.2.20 on 2025-05-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('faction', models.CharField(choices=[('AXIOM', 'Axiom'), ('BRAVOS', 'Bravos'), ('LYRA', 'Lyra'), ('MUNA', 'Muna'), ('ORDIS', 'Ordis'), ('YZMIR', 'Yzmir')], max_length=8)),
                ('altered_id', models.CharField(max_length=20)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='altered.champion')),
            ],
        ),
        migrations.CreateModel(
            name='DeckVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='altered.deck')),
            ],
        ),
    ]
