# Generated by Django 4.2.20 on 2025-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0002_deck_deckversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='altered_id',
            field=models.CharField(max_length=32),
        ),
    ]
