# Generated by Django 4.2.20 on 2025-05-30 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0003_alter_deck_altered_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
