# Generated by Django 4.2.20 on 2025-05-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0004_deckversion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='faction',
        ),
    ]
