# Generated by Django 4.2.20 on 2025-05-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0005_remove_deck_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_win', models.BooleanField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='altered.deck')),
                ('deck_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='altered.deckversion')),
                ('opponent_champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='altered.champion')),
            ],
        ),
    ]
