# Generated by Django 4.2.20 on 2025-05-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='altered.deckversion'),
        ),
    ]
