# Generated by Django 4.2.20 on 2025-06-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0008_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
