# Generated by Django 4.2.20 on 2025-06-04 07:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0009_delete_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckversion',
            name='change_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
