# Generated by Django 4.2.20 on 2025-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0010_deckversion_change_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
