# Generated by Django 4.2.20 on 2025-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("altered", "0011_deck_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueFlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=128, unique=True)),
                ("bought_at", models.DateTimeField()),
                ("bought_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
