# Generated by Django 4.2.20 on 2025-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("altered", "0012_uniqueflip"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniqueflip",
            name="name",
            field=models.CharField(max_length=128, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="uniqueflip",
            name="image_path",
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
    ]
