# Generated by Django 4.2.20 on 2025-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0013_uniqueflip_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueflip',
            name='faction',
            field=models.CharField(blank=True, choices=[('AXIOM', 'Axiom'), ('BRAVOS', 'Bravos'), ('LYRA', 'Lyra'), ('MUNA', 'Muna'), ('ORDIS', 'Ordis'), ('YZMIR', 'Yzmir')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='uniqueflip',
            name='forest_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueflip',
            name='main_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueflip',
            name='mountain_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueflip',
            name='ocean_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueflip',
            name='recall_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
