# Generated by Django 4.2.20 on 2025-07-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0014_uniqueflip_faction_uniqueflip_forest_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueflip',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
