# Generated by Django 4.2.20 on 2025-10-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0015_uniqueflip_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unique_flip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='altered.uniqueflip')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
