# Generated by Django 4.2.20 on 2025-10-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0016_uniqueprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(choices=[('BEYONG_THE_GATE', 'Beyong the gate'), ('TRIAL_BY_FROST', 'Trial by frost'), ('WHISPERS_FROM_THE_MAZE', 'Whispers from the maze'), ('SKYBOUND_ODYSSEY', 'Skybound Odyssey')], max_length=32)),
                ('hand_cost', models.PositiveIntegerField()),
                ('reserve_cost', models.PositiveIntegerField()),
                ('faction', models.CharField(choices=[('AXIOM', 'Axiom'), ('BRAVOS', 'Bravos'), ('LYRA', 'Lyra'), ('MUNA', 'Muna'), ('ORDIS', 'Ordis'), ('YZMIR', 'Yzmir')], max_length=8)),
                ('forest_amount', models.PositiveIntegerField(default=0)),
                ('water_amount', models.PositiveIntegerField(default=0)),
                ('mountain_amount', models.PositiveIntegerField(default=0)),
                ('effects', models.JSONField(blank=True, default=list)),
                ('rarity', models.CharField(choices=[('COMMON', 'Commun'), ('RARE', 'Rare'), ('UNIQUE', 'Unique')], max_length=16)),
                ('altered_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('name', 'extension'),
            },
        ),
        migrations.CreateModel(
            name='CardWithQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='altered.card')),
                ('deck_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_quantities', to='altered.deckversion')),
            ],
            options={
                'unique_together': {('card', 'deck_version')},
            },
        ),
        migrations.AddField(
            model_name='deckversion',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='deck_versions', through='altered.CardWithQuantity', to='altered.card'),
        ),
    ]
