# Generated by ChatGPT on 2025-10-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altered', '0017_card_cardwithquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckversion',
            name='cards',
        ),
    ]
