# Generated by Django 4.2.20 on 2025-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("speedrun", "Speedrun"),
                            ("steel_soul", "Steel Soul"),
                            ("boss_fight", "Boss Fight"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boss",
                    models.CharField(
                        blank=True,
                        choices=[("Lace 1", "Lace 1"), ("Gruz Mother", "Gruz Mother")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("death_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "death_explanation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lace 1", "Lace 1"),
                            ("Gruz Mother", "Gruz Mother"),
                            ("Arena 1", "Arena 1"),
                            ("Arena 2", "Arena 2"),
                            ("Moss", "Moss"),
                            ("Deep work", "Deep work"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("victory", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
