# Generated by Django 4.2.20 on 2025-09-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silksong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='boss',
            field=models.CharField(blank=True, choices=[('Lace 1', 'Lace 1'), ('Gruz Mother', 'Gruz Mother'), ('Trobio', 'Trobio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='death_explanation',
            field=models.CharField(blank=True, choices=[('Lace 1', 'Lace 1'), ('Gruz Mother', 'Gruz Mother'), ('Trobio', 'Trobio'), ('Arena 1', 'Arena 1'), ('Arena 2', 'Arena 2'), ('Moss', 'Moss'), ('Deep work', 'Deep work')], max_length=50, null=True),
        ),
    ]
