# Generated by Django 4.2.20 on 2025-09-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silksong', '0002_alter_gamesession_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='boss',
            field=models.CharField(blank=True, choices=[('Bell Beast', 'Bell Beast'), ('Bell Eater', 'Bell Eater'), ('Broodmother', 'Broodmother'), ('Carmelita', 'Carmelita'), ('Clover Dancers', 'Clover Dancers'), ('Cogwork Dancers', 'Cogwork Dancers'), ('Craggler', 'Craggler'), ('Crawfather', 'Crawfather'), ('Crust King Khann', 'Crust King Khann'), ('Disgraced Chef Lugoli', 'Disgraced Chef Lugoli'), ('Father of the Flame', 'Father of the Flame'), ('First Sinner', 'First Sinner'), ('Fourth Chorus', 'Fourth Chorus'), ('Garmond and Zaza', 'Garmond and Zaza'), ('Grand Mother Silk', 'Grand Mother Silk'), ('Great Conchflies', 'Great Conchflies'), ('Groal the Great', 'Groal the Great'), ('Gurr the Outcast', 'Gurr the Outcast'), ('Lace', 'Lace'), ('Last Judge', 'Last Judge'), ('Lost Garmond', 'Lost Garmond'), ('Lost Lace', 'Lost Lace'), ('Moorwing', 'Moorwing'), ('Moss Mother', 'Moss Mother'), ('Nyleth', 'Nyleth'), ('Palestag', 'Palestag'), ('Phantom', 'Phantom'), ('Pinstress', 'Pinstress'), ('Plasmified Zango', 'Plasmified Zango'), ('Raging Conchfly', 'Raging Conchfly'), ('Savage Beastfly', 'Savage Beastfly'), ('Second Sentinel', 'Second Sentinel'), ('Shakra', 'Shakra'), ('Shrine Guardian Seth', 'Shrine Guardian Seth'), ('Signis and Gron', 'Signis and Gron'), ('Sister Splinter', 'Sister Splinter'), ('Skull Tyrant', 'Skull Tyrant'), ('Summoned Saviour', 'Summoned Saviour'), ('The Unraveled', 'The Unraveled'), ('Tormented Trobbio', 'Tormented Trobbio'), ('Trobbio', 'Trobbio'), ('Voltvyrm', 'Voltvyrm'), ('Watcher at the Edge', 'Watcher at the Edge'), ('Widow', 'Widow')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='death_explanation',
            field=models.CharField(blank=True, choices=[('Bell Beast', 'Bell Beast'), ('Bell Eater', 'Bell Eater'), ('Broodmother', 'Broodmother'), ('Carmelita', 'Carmelita'), ('Clover Dancers', 'Clover Dancers'), ('Cogwork Dancers', 'Cogwork Dancers'), ('Craggler', 'Craggler'), ('Crawfather', 'Crawfather'), ('Crust King Khann', 'Crust King Khann'), ('Disgraced Chef Lugoli', 'Disgraced Chef Lugoli'), ('Father of the Flame', 'Father of the Flame'), ('First Sinner', 'First Sinner'), ('Fourth Chorus', 'Fourth Chorus'), ('Garmond and Zaza', 'Garmond and Zaza'), ('Grand Mother Silk', 'Grand Mother Silk'), ('Great Conchflies', 'Great Conchflies'), ('Groal the Great', 'Groal the Great'), ('Gurr the Outcast', 'Gurr the Outcast'), ('Lace', 'Lace'), ('Last Judge', 'Last Judge'), ('Lost Garmond', 'Lost Garmond'), ('Lost Lace', 'Lost Lace'), ('Moorwing', 'Moorwing'), ('Moss Mother', 'Moss Mother'), ('Nyleth', 'Nyleth'), ('Palestag', 'Palestag'), ('Phantom', 'Phantom'), ('Pinstress', 'Pinstress'), ('Plasmified Zango', 'Plasmified Zango'), ('Raging Conchfly', 'Raging Conchfly'), ('Savage Beastfly', 'Savage Beastfly'), ('Second Sentinel', 'Second Sentinel'), ('Shakra', 'Shakra'), ('Shrine Guardian Seth', 'Shrine Guardian Seth'), ('Signis and Gron', 'Signis and Gron'), ('Sister Splinter', 'Sister Splinter'), ('Skull Tyrant', 'Skull Tyrant'), ('Summoned Saviour', 'Summoned Saviour'), ('The Unraveled', 'The Unraveled'), ('Tormented Trobbio', 'Tormented Trobbio'), ('Trobbio', 'Trobbio'), ('Voltvyrm', 'Voltvyrm'), ('Watcher at the Edge', 'Watcher at the Edge'), ('Widow', 'Widow'), ('Arena 1', 'Arena 1'), ('Arena 2', 'Arena 2'), ('Moss', 'Moss'), ('Deep work', 'Deep work')], max_length=50, null=True),
        ),
    ]
