# Generated by Django 4.2.20 on 2025-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_alter_bazaarrun_archetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaarrun',
            name='archetype',
            field=models.CharField(blank=True, choices=[('FIXER_UPPER', 'Fixer Upper'), ('SINGLE_WEAPON', 'Single Weapon'), ('PUFFERFISH', 'Pufferfish'), ('LIGHTHOUSE_BURN', 'Lighthouse Burn'), ('DOUBLE_WHAMMY', 'Double Whammy'), ('POWER_DRILL', 'Power Drill'), ('SPIDER_MACE', 'Spider Mace'), ('BOTTLED_EXPLOSION', 'Bottled Explosion'), ('ACID_VAT', 'Vat of Acid')], max_length=17, null=True),
        ),
    ]
