# Generated by Django 4.2.20 on 2025-04-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_alter_bazaarrun_archetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazaarrun',
            options={'permissions': [('bazaar_access', 'Can access bazaar pages')]},
        ),
    ]
