# Generated by Django 4.2.20 on 2025-04-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0009_bazaarseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaarrun',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habit_tracker.bazaarseason'),
        ),
    ]
