# Generated by Django 4.2.20 on 2026-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runfile',
            name='parsed_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='runfile',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
