# Generated by Django 4.2.20 on 2026-04-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0002_runfile_parsed_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField()),
                ('abandonned', models.BooleanField()),
                ('ascension', models.IntegerField()),
                ('killed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='slay_the_spire2.runfile')),
            ],
        ),
    ]
