# Generated by Django 4.2.20 on 2026-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0003_runsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsummary',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
