# Generated by Django 4.2.20 on 2026-04-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0005_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsummary',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_summaries', to='slay_the_spire2.character'),
        ),
    ]
