# Generated by Django 4.2.20 on 2026-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0006_runsummary_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ancient', 'Ancient'), ('monster', 'Monster'), ('room', 'Room'), ('elite', 'Elite'), ('boss', 'Boss')], max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
