# Generated by Django 4.2.20 on 2026-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0007_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='type',
            field=models.CharField(choices=[('ancient', 'Ancient'), ('monster', 'Monster'), ('room', 'Room'), ('elite', 'Elite'), ('boss', 'Boss'), ('rest_site', 'RestSite')], max_length=20),
        ),
    ]
