# Generated by Django 4.2.20 on 2026-04-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0009_alter_encounter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runsummary',
            name='killed_by',
        ),
        migrations.AddField(
            model_name='runsummary',
            name='killed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killed_run_summaries', to='slay_the_spire2.encounter'),
        ),
    ]
