# Generated by Django 4.2.20 on 2026-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0011_relic'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsummary',
            name='relics',
            field=models.ManyToManyField(blank=True, related_name='run_summaries', to='slay_the_spire2.relic'),
        ),
    ]
