# Generated by Django 4.2.20 on 2026-04-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0013_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_summary_entries', to='slay_the_spire2.card')),
                ('run_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_entries', to='slay_the_spire2.runsummary')),
            ],
        ),
        migrations.AddField(
            model_name='runsummary',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='run_summaries', through='slay_the_spire2.RunSummaryCard', to='slay_the_spire2.card'),
        ),
        migrations.AddIndex(
            model_name='runsummarycard',
            index=models.Index(fields=['run_summary'], name='sts_rsc_run_summary_idx'),
        ),
        migrations.AddIndex(
            model_name='runsummarycard',
            index=models.Index(fields=['card'], name='sts_rsc_card_idx'),
        ),
        migrations.AddConstraint(
            model_name='runsummarycard',
            constraint=models.UniqueConstraint(fields=('run_summary', 'card'), name='sts_unique_run_summary_card'),
        ),
    ]
