# Generated by Django 4.2.20 on 2026-04-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0014_runsummarycard_runsummary_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_taken', models.IntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_encounters', to='slay_the_spire2.encounter')),
                ('run_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='slay_the_spire2.runsummary')),
            ],
            options={
                'indexes': [models.Index(fields=['run_summary'], name='sts_re_run_summary_idx'), models.Index(fields=['encounter'], name='sts_re_encounter_idx')],
            },
        ),
    ]
