# Generated by Django 4.2.20 on 2026-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slay_the_spire2", "0015_runencounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="runencounter",
            name="floor",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
