# Generated by Django 4.2.20 on 2026-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0016_runencounter_floor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runencounter',
            constraint=models.UniqueConstraint(fields=('run_summary', 'floor'), name='sts_unique_run_summary_floor'),
        ),
    ]
