# Generated by Django 4.2.20 on 2026-04-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slay_the_spire2", "0017_runencounter_sts_unique_run_summary_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="runencounter",
            name="act",
            field=models.IntegerField(
                choices=[
                    (0, "Act 1"),
                    (1, "Act 2"),
                    (2, "Act 3"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name="runencounter",
            name="sts_unique_run_summary_floor",
        ),
        migrations.AddConstraint(
            model_name="runencounter",
            constraint=models.UniqueConstraint(
                fields=("run_summary", "floor", "act"),
                name="sts_unique_run_summary_floor_act",
            ),
        ),
        migrations.AddConstraint(
            model_name="runencounter",
            constraint=models.CheckConstraint(
                check=models.Q(act__in=[0, 1, 2]),
                name="sts_run_encounter_act_valid",
            ),
        ),
    ]
