# Generated by Django 4.2.20 on 2026-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slay_the_spire2', '0018_runencounter_act_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='type',
            field=models.CharField(choices=[('ancient', 'Ancient'), ('monster', 'Monster'), ('shop', 'Shop'), ('room', 'Room'), ('elite', 'Elite'), ('boss', 'Boss'), ('rest_site', 'RestSite'), ('treasure', 'Treasure')], max_length=20),
        ),
    ]
