from django.db import models


class Boss(models.TextChoices):
    BELL_BEAST = "Bell Beast", "Bell Beast"
    BELL_EATER = "Bell Eater", "Bell Eater"
    BROODMOTHER = "Broodmother", "Broodmother"
    CARMELITA = "Carmelita", "Carmelita"
    CLOVER_DANCERS = "Clover Dancers", "Clover Dancers"
    COGWORK_DANCERS = "Cogwork Dancers", "Cogwork Dancers"
    CRAGGLER = "Craggler", "Craggler"
    CRAWFATHER = "Crawfather", "Crawfather"
    CRUST_KING_KHANN = "Crust King Khann", "Crust King Khann"
    DISGRACED_CHEF_LUGOLI = "Disgraced Chef Lugoli", "Disgraced Chef Lugoli"
    FATHER_OF_THE_FLAME = "Father of the Flame", "Father of the Flame"
    FIRST_SINNER = "First Sinner", "First Sinner"
    FOURTH_CHORUS = "Fourth Chorus", "Fourth Chorus"
    GARMOND_AND_ZAZA = "Garmond and Zaza", "Garmond and Zaza"
    GRAND_MOTHER_SILK = "Grand Mother Silk", "Grand Mother Silk"
    GREAT_CONCHFLIES = "Great Conchflies", "Great Conchflies"
    GROAL_THE_GREAT = "Groal the Great", "Groal the Great"
    GURR_THE_OUTCAST = "Gurr the Outcast", "Gurr the Outcast"
    LACE = "Lace", "Lace"
    LAST_JUDGE = "Last Judge", "Last Judge"
    LOST_GARMOND = "Lost Garmond", "Lost Garmond"
    LOST_LACE = "Lost Lace", "Lost Lace"
    MOORWING = "Moorwing", "Moorwing"
    MOSS_MOTHER = "Moss Mother", "Moss Mother"
    NYLETH = "Nyleth", "Nyleth"
    PALESTAG = "Palestag", "Palestag"
    PHANTOM = "Phantom", "Phantom"
    PINSTRESS = "Pinstress", "Pinstress"
    PLASMIFIED_ZANGO = "Plasmified Zango", "Plasmified Zango"
    RAGING_CONCHFLY = "Raging Conchfly", "Raging Conchfly"
    SAVAGE_BEASTFLY = "Savage Beastfly", "Savage Beastfly"
    SECOND_SENTINEL = "Second Sentinel", "Second Sentinel"
    SHAKRA = "Shakra", "Shakra"
    SHRINE_GUARDIAN_SETH = "Shrine Guardian Seth", "Shrine Guardian Seth"
    SIGNIS_AND_GRON = "Signis and Gron", "Signis and Gron"
    SISTER_SPLINTER = "Sister Splinter", "Sister Splinter"
    SKULL_TYRANT = "Skull Tyrant", "Skull Tyrant"
    SUMMONED_SAVIOUR = "Summoned Saviour", "Summoned Saviour"
    THE_UNRAVELED = "The Unraveled", "The Unraveled"
    TORMENTED_TROBBIO = "Tormented Trobbio", "Tormented Trobbio"
    TROBBIO = "Trobbio", "Trobbio"
    VOLTVYRM = "Voltvyrm", "Voltvyrm"
    WATCHER_AT_THE_EDGE = "Watcher at the Edge", "Watcher at the Edge"
    WIDOW = "Widow", "Widow"
