# Generated by Django 4.2.20 on 2025-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STAG', 'Stag'), ('GOAT', 'Goat'), ('WOLF', 'Wolf'), ('RAVEN', 'Raven'), ('BEAR', 'Bear'), ('BOAR', 'Boar'), ('SNAKE', 'Snake'), ('DRAGON', 'Dragon'), ('HORSE', 'Horse'), ('OX', 'Ox'), ('LYNX', 'Lynx'), ('SQUIRREL', 'Squirrel'), ('RAT', 'Rat'), ('EAGLE', 'Eagle'), ('LION', 'Lion'), ('STOAT', 'Stoat'), ('OWL', 'Owl'), ('HOUND', 'Hound'), ('TURTLE', 'Turtle')], default='STAG', max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='northguard/clan_images/')),
            ],
        ),
    ]
