# Generated by Django 4.2.20 on 2025-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(choices=[('STAG', 'Stag'), ('GOAT', 'Goat'), ('WOLF', 'Wolf'), ('RAVEN', 'Raven'), ('BEAR', 'Bear'), ('BOAR', 'Boar'), ('SNAKE', 'Snake'), ('DRAGON', 'Dragon'), ('HORSE', 'Horse'), ('OX', 'Ox'), ('LYNX', 'Lynx'), ('SQUIRREL', 'Squirrel'), ('RAT', 'Rat'), ('EAGLE', 'Eagle'), ('LION', 'Lion'), ('STOAT', 'Stoat'), ('OWL', 'Owl'), ('HOUND', 'Hound'), ('TURTLE', 'Turtle')], default='STAG', max_length=8, unique=True),
        ),
    ]
