# Generated by Django 4.2.20 on 2025-05-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('northguard', '0002_alter_clan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildOrderMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCOUT', 'Scout'), ('LUMBERJACK', 'Lumberjack')], default='SCOUT', max_length=10, unique=True)),
                ('type', models.CharField(choices=[('BUILDING', 'Building'), ('TECHNOLOGY', 'Technology')], default='BUILDING', max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='northguard/milestone_image/')),
            ],
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(choices=[('BEAR', 'Bear'), ('BOAR', 'Boar'), ('DRAGON', 'Dragon'), ('EAGLE', 'Eagle'), ('GOAT', 'Goat'), ('HORSE', 'Horse'), ('HOUND', 'Hound'), ('LION', 'Lion'), ('LYNX', 'Lynx'), ('OWL', 'Owl'), ('OX', 'Ox'), ('RAT', 'Rat'), ('RAVEN', 'Raven'), ('SNAKE', 'Snake'), ('SQUIRREL', 'Squirrel'), ('STAG', 'Stag'), ('STOAT', 'Stoat'), ('TURTLE', 'Turtle'), ('WOLF', 'Wolf')], default='STAG', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='BuildOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=8, null=True)),
                ('state_of_the_art', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_orders', to='northguard.clan')),
            ],
        ),
    ]
