# Generated by Django 4.2.20 on 2025-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northguard', '0004_buildorderstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildordermilestone',
            name='type',
            field=models.CharField(choices=[('BUILDING', 'Building'), ('TECHNOLOGY', 'Technology')], default='BUILDING', max_length=10),
        ),
    ]
