# Generated by Django 4.2.20 on 2025-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northguard', '0005_alter_buildordermilestone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(choices=[('BEAR', 'Bear'), ('BOAR', 'Boar'), ('DRAGON', 'Dragon'), ('EAGLE', 'Eagle'), ('GOAT', 'Goat'), ('HORSE', 'Horse'), ('HOUND', 'Hound'), ('LION', 'Lion'), ('LYNX', 'Lynx'), ('OWL', 'Owl'), ('OX', 'Ox'), ('RAT', 'Rat'), ('RAVEN', 'Raven'), ('SNAKE', 'Snake'), ('SQUIRREL', 'Squirrel'), ('STAG', 'Stag'), ('STOAT', 'Stoat'), ('TURTLE', 'Turtle'), ('WOLF', 'Wolf'), ('KRAKEN', 'Kraken')], default='STAG', max_length=8, unique=True),
        ),
    ]
