# Generated by Django 4.2.20 on 2025-09-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Civilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "epoque",
                    models.CharField(
                        choices=[
                            ("ANTIQUITE", "Antiquité"),
                            ("EXPLORATION", "Exploration"),
                            ("MODERNE", "Moderne"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wonder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "epoque",
                    models.CharField(
                        choices=[
                            ("ANTIQUITE", "Antiquité"),
                            ("EXPLORATION", "Exploration"),
                            ("MODERNE", "Moderne"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("victory", models.BooleanField(default=False)),
                (
                    "victory_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CULTURE", "Culture"),
                            ("SCIENTIFIQUE", "Scientifique"),
                            ("COMMERCIALE", "Commerciale"),
                            ("MILITAIRE", "Militaire"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "civ_antiquite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_antiquite",
                        to="civilization7.civilization",
                    ),
                ),
                (
                    "civ_exploration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_exploration",
                        to="civilization7.civilization",
                    ),
                ),
                (
                    "civ_moderne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_moderne",
                        to="civilization7.civilization",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="civilization7.leader",
                    ),
                ),
            ],
        ),
    ]
