# Generated by Django 4.2.20 on 2025-09-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Civilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                (
                    "era",
                    models.CharField(
                        choices=[
                            ("ANCIENT", "Antiquité"),
                            ("EXPLORATION", "Exploration"),
                            ("MODERN", "Moderne"),
                        ],
                        max_length=20,
                        verbose_name="Époque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wonder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                (
                    "era",
                    models.CharField(
                        choices=[
                            ("ANCIENT", "Antiquité"),
                            ("EXPLORATION", "Exploration"),
                            ("MODERN", "Moderne"),
                        ],
                        max_length=20,
                        verbose_name="Époque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "victory",
                    models.BooleanField(default=False, verbose_name="Victoire"),
                ),
                (
                    "victory_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CULTURE", "Culture"),
                            ("SCIENCE", "Scientifique"),
                            ("COMMERCIAL", "Commerciale"),
                            ("MILITARY", "Militaire"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Type de victoire",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "ancient_civ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_ancient",
                        to="civilization7.civilization",
                        verbose_name="Antiquité",
                    ),
                ),
                (
                    "exploration_civ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_exploration",
                        to="civilization7.civilization",
                        verbose_name="Exploration",
                    ),
                ),
                (
                    "modern_civ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_modern",
                        to="civilization7.civilization",
                        verbose_name="Moderne",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="civilization7.leader",
                        verbose_name="Leader",
                    ),
                ),
            ],
        ),
    ]
