# Generated by Django 4.2.20 on 2025-08-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bttdobject',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
