# Generated by Django 4.2.20 on 2024-08-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games_collection", "0002_alter_bttdobject_base_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="BttdPossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possessions",
                        to="games_collection.bttdanimal",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possessions",
                        to="games_collection.bttdobject",
                    ),
                ),
            ],
            options={"unique_together": {("animal", "object")}},
        ),
    ]

