ARTIFACT_SALVAGE_FAMILIES = (
    {
        "key": "rune",
        "label": "Rune",
        "shard_label": "Rune",
        "shard_aodp_id_fragment": "RUNE",
        "artifacts": (
            {"label": "Bloodforged Blade", "aodp_id_fragment": "ARTEFACT_MAIN_SCIMITAR_MORGANA"},
            {"label": "Ancient Halberd Head", "aodp_id_fragment": "ARTEFACT_2H_HALBERD_MORGANA"},
            {"label": "Runed Rock", "aodp_id_fragment": "ARTEFACT_MAIN_ROCKMACE_KEEPER"},
            {"label": "Ancient Hammer Head", "aodp_id_fragment": "ARTEFACT_2H_HAMMER_UNDEAD"},
            {"label": "Ursine Guardian Remains", "aodp_id_fragment": "ARTEFACT_2H_KNUCKLES_KEEPER"},
            {"label": "Lost Crossbow Mechanism", "aodp_id_fragment": "ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD"},
            {"label": "Ancient Shield Core", "aodp_id_fragment": "ARTEFACT_OFF_TOWERSHIELD_UNDEAD"},
            {"label": "Ancient Padding", "aodp_id_fragment": "ARTEFACT_HEAD_PLATE_UNDEAD"},
            {"label": "Ancient Chain Rings", "aodp_id_fragment": "ARTEFACT_ARMOR_PLATE_UNDEAD"},
            {"label": "Ancient Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_PLATE_UNDEAD"},
            {"label": "Ghastly Arrows", "aodp_id_fragment": "ARTEFACT_2H_LONGBOW_UNDEAD"},
            {"label": "Keeper Spearhead", "aodp_id_fragment": "ARTEFACT_MAIN_SPEAR_KEEPER"},
            {"label": "Druidic Inscriptions", "aodp_id_fragment": "ARTEFACT_MAIN_NATURESTAFF_KEEPER"},
            {"label": "Hardened Debole", "aodp_id_fragment": "ARTEFACT_MAIN_RAPIER_MORGANA"},
            {"label": "Reinforced Morgana Pole", "aodp_id_fragment": "ARTEFACT_2H_COMBATSTAFF_MORGANA"},
            {"label": "Werewolf Remnant", "aodp_id_fragment": "ARTEFACT_2H_SHAPESHIFTER_MORGANA"},
            {"label": "Runed Horn", "aodp_id_fragment": "ARTEFACT_OFF_HORN_KEEPER"},
            {"label": "Imbued Visor", "aodp_id_fragment": "ARTEFACT_HEAD_LEATHER_MORGANA"},
            {"label": "Imbued Leather Folds", "aodp_id_fragment": "ARTEFACT_ARMOR_LEATHER_MORGANA"},
            {"label": "Imbued Soles", "aodp_id_fragment": "ARTEFACT_SHOES_LEATHER_MORGANA"},
            {"label": "Wildfire Orb", "aodp_id_fragment": "ARTEFACT_MAIN_FIRESTAFF_KEEPER"},
            {"label": "Possessed Scroll", "aodp_id_fragment": "ARTEFACT_MAIN_HOLYSTAFF_MORGANA"},
            {"label": "Lost Arcane Crystal", "aodp_id_fragment": "ARTEFACT_MAIN_ARCANESTAFF_UNDEAD"},
            {"label": "Hoarfrost Orb", "aodp_id_fragment": "ARTEFACT_MAIN_FROSTSTAFF_KEEPER"},
            {"label": "Lost Cursed Crystal", "aodp_id_fragment": "ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD"},
            {"label": "Alluring Crystal", "aodp_id_fragment": "ARTEFACT_OFF_ORB_MORGANA"},
            {"label": "Druidic Preserved Beak", "aodp_id_fragment": "ARTEFACT_HEAD_CLOTH_KEEPER"},
            {"label": "Druidic Feathers", "aodp_id_fragment": "ARTEFACT_ARMOR_CLOTH_KEEPER"},
            {"label": "Druidic Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_CLOTH_KEEPER"},
        ),
    },
    {
        "key": "soul",
        "label": "Soul",
        "shard_label": "Soul",
        "shard_aodp_id_fragment": "SOUL",
        "artifacts": (
            {"label": "Burning Orb", "aodp_id_fragment": "ARTEFACT_2H_FIRESTAFF_HELL"},
            {"label": "Infernal Scroll", "aodp_id_fragment": "ARTEFACT_2H_HOLYSTAFF_HELL"},
            {"label": "Occult Orb", "aodp_id_fragment": "ARTEFACT_2H_ARCANESTAFF_HELL"},
            {"label": "Icicle Orb", "aodp_id_fragment": "ARTEFACT_2H_ICEGAUNTLETS_HELL"},
            {"label": "Cursed Jawbone", "aodp_id_fragment": "ARTEFACT_2H_SKULLORB_HELL"},
            {"label": "Demonic Jawbone", "aodp_id_fragment": "ARTEFACT_OFF_DEMONSKULL_HELL"},
            {"label": "Infernal Cloth Visor", "aodp_id_fragment": "ARTEFACT_HEAD_CLOTH_HELL"},
            {"label": "Infernal Cloth Folds", "aodp_id_fragment": "ARTEFACT_ARMOR_CLOTH_HELL"},
            {"label": "Infernal Cloth Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_CLOTH_HELL"},
            {"label": "Demonic Arrowheads", "aodp_id_fragment": "ARTEFACT_2H_BOW_HELL"},
            {"label": "Infernal Harpoon Tip", "aodp_id_fragment": "ARTEFACT_2H_HARPOON_HELL"},
            {"label": "Symbol of Blight", "aodp_id_fragment": "ARTEFACT_2H_NATURESTAFF_HELL"},
            {"label": "Broken Demonic Fang", "aodp_id_fragment": "ARTEFACT_MAIN_DAGGER_HELL"},
            {"label": "Hellfire Imp Remnant", "aodp_id_fragment": "ARTEFACT_2H_SHAPESHIFTER_HELL"},
            {"label": "Hellish Handle", "aodp_id_fragment": "ARTEFACT_OFF_JESTERCANE_HELL"},
            {"label": "Demonhide Padding", "aodp_id_fragment": "ARTEFACT_HEAD_LEATHER_HELL"},
            {"label": "Demonhide Leather", "aodp_id_fragment": "ARTEFACT_ARMOR_LEATHER_HELL"},
            {"label": "Demonhide Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_LEATHER_HELL"},
            {"label": "Demonic Blade", "aodp_id_fragment": "ARTEFACT_2H_CLEAVER_HELL"},
            {"label": "Hellish Sicklehead", "aodp_id_fragment": "ARTEFACT_2H_SCYTHE_HELL"},
            {"label": "Infernal Mace Head", "aodp_id_fragment": "ARTEFACT_MAIN_MACE_HELL"},
            {"label": "Hellish Hammer Heads", "aodp_id_fragment": "ARTEFACT_2H_DUALHAMMER_HELL"},
            {"label": "Severed Demonic Horns", "aodp_id_fragment": "ARTEFACT_2H_KNUCKLES_HELL"},
            {"label": "Hellish Bolts", "aodp_id_fragment": "ARTEFACT_2H_DUALCROSSBOW_HELL"},
            {"label": "Infernal Shield Core", "aodp_id_fragment": "ARTEFACT_OFF_SHIELD_HELL"},
            {"label": "Demonic Scraps", "aodp_id_fragment": "ARTEFACT_HEAD_PLATE_HELL"},
            {"label": "Demonic Plates", "aodp_id_fragment": "ARTEFACT_ARMOR_PLATE_HELL"},
            {"label": "Demonic Filling", "aodp_id_fragment": "ARTEFACT_SHOES_PLATE_HELL"},
            {"label": "Hellish Sicklehead Pair", "aodp_id_fragment": "ARTEFACT_2H_TWINSCYTHE_HELL"},
        ),
    },
    {
        "key": "relic",
        "label": "Relic",
        "shard_label": "Relic",
        "shard_aodp_id_fragment": "RELIC",
        "artifacts": (
            {"label": "Unholy Scroll", "aodp_id_fragment": "ARTEFACT_2H_INFERNOSTAFF_MORGANA"},
            {"label": "Ghastly Scroll", "aodp_id_fragment": "ARTEFACT_2H_HOLYSTAFF_UNDEAD"},
            {"label": "Possessed Catalyst", "aodp_id_fragment": "ARTEFACT_2H_ENIGMATICORB_MORGANA"},
            {"label": "Cursed Frozen Crystal", "aodp_id_fragment": "ARTEFACT_2H_ICECRYSTAL_UNDEAD"},
            {"label": "Bloodforged Catalyst", "aodp_id_fragment": "ARTEFACT_2H_CURSEDSTAFF_MORGANA"},
            {"label": "Inscribed Stone", "aodp_id_fragment": "ARTEFACT_OFF_TOTEM_KEEPER"},
            {"label": "Alluring Padding", "aodp_id_fragment": "ARTEFACT_HEAD_CLOTH_MORGANA"},
            {"label": "Alluring Amulet", "aodp_id_fragment": "ARTEFACT_ARMOR_CLOTH_MORGANA"},
            {"label": "Alluring Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_CLOTH_MORGANA"},
            {"label": "Carved Bone", "aodp_id_fragment": "ARTEFACT_2H_BOW_KEEPER"},
            {"label": "Cursed Barbs", "aodp_id_fragment": "ARTEFACT_2H_TRIDENT_UNDEAD"},
            {"label": "Preserved Log", "aodp_id_fragment": "ARTEFACT_2H_NATURESTAFF_KEEPER"},
            {"label": "Ghastly Blades", "aodp_id_fragment": "ARTEFACT_2H_DUALSICKLE_UNDEAD"},
            {"label": "Preserved Rocks", "aodp_id_fragment": "ARTEFACT_2H_ROCKSTAFF_KEEPER"},
            {"label": "Runestone Golem Remnant", "aodp_id_fragment": "ARTEFACT_2H_SHAPESHIFTER_KEEPER"},
            {"label": "Ghastly Candle", "aodp_id_fragment": "ARTEFACT_OFF_LAMP_UNDEAD"},
            {"label": "Ghastly Visor", "aodp_id_fragment": "ARTEFACT_HEAD_LEATHER_UNDEAD"},
            {"label": "Ghastly Leather", "aodp_id_fragment": "ARTEFACT_ARMOR_LEATHER_UNDEAD"},
            {"label": "Ghastly Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_LEATHER_UNDEAD"},
            {"label": "Cursed Blades", "aodp_id_fragment": "ARTEFACT_2H_DUALSCIMITAR_UNDEAD"},
            {"label": "Keeper Axeheads", "aodp_id_fragment": "ARTEFACT_2H_DUALAXE_KEEPER"},
            {"label": "Imbued Mace Head", "aodp_id_fragment": "ARTEFACT_2H_MACE_MORGANA"},
            {"label": "Engraved Log", "aodp_id_fragment": "ARTEFACT_2H_RAM_KEEPER"},
            {"label": "Warped Raven Plate", "aodp_id_fragment": "ARTEFACT_2H_KNUCKLES_MORGANA"},
            {"label": "Alluring Bolts", "aodp_id_fragment": "ARTEFACT_2H_CROSSBOWLARGE_MORGANA"},
            {"label": "Bloodforged Spikes", "aodp_id_fragment": "ARTEFACT_OFF_SPIKEDSHIELD_MORGANA"},
            {"label": "Carved Skull Padding", "aodp_id_fragment": "ARTEFACT_HEAD_PLATE_KEEPER"},
            {"label": "Preserved Animal Fur", "aodp_id_fragment": "ARTEFACT_ARMOR_PLATE_KEEPER"},
            {"label": "Inscribed Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_PLATE_KEEPER"},
        ),
    },
    {
        "key": "avalonian",
        "label": "Avalonian",
        "shard_label": "Avalonian",
        "shard_aodp_id_fragment": "SHARD_AVALONIAN",
        "artifacts": (
            {"label": "Glowing Harmonic Ring", "aodp_id_fragment": "ARTEFACT_2H_FIRE_RINGPAIR_AVALON"},
            {"label": "Hypnotic Harmonic Ring", "aodp_id_fragment": "ARTEFACT_2H_ARCANE_RINGPAIR_AVALON"},
            {"label": "Messianic Curio", "aodp_id_fragment": "ARTEFACT_MAIN_HOLYSTAFF_AVALON"},
            {"label": "Chilled Crystalline Shard", "aodp_id_fragment": "ARTEFACT_MAIN_FROSTSTAFF_AVALON"},
            {"label": "Fractured Opaque Orb", "aodp_id_fragment": "ARTEFACT_MAIN_CURSEDSTAFF_AVALON"},
            {"label": "Severed Celestial Keepsake", "aodp_id_fragment": "ARTEFACT_OFF_CENSER_AVALON"},
            {"label": "Sanctified Mask", "aodp_id_fragment": "ARTEFACT_HEAD_CLOTH_AVALON"},
            {"label": "Sanctified Belt", "aodp_id_fragment": "ARTEFACT_ARMOR_CLOTH_AVALON"},
            {"label": "Sanctified Bindings", "aodp_id_fragment": "ARTEFACT_SHOES_CLOTH_AVALON"},
            {"label": "Immaculately Crafted Riser", "aodp_id_fragment": "ARTEFACT_2H_BOW_AVALON"},
            {"label": "Ruined Ancestral Vamplate", "aodp_id_fragment": "ARTEFACT_MAIN_SPEAR_LANCE_AVALON"},
            {"label": "Uprooted Perennial Sapling", "aodp_id_fragment": "ARTEFACT_MAIN_NATURESTAFF_AVALON"},
            {"label": "Bloodstained Antiquities", "aodp_id_fragment": "ARTEFACT_2H_DAGGER_KATAR_AVALON"},
            {"label": "Timeworn Walking Staff", "aodp_id_fragment": "ARTEFACT_2H_QUARTERSTAFF_AVALON"},
            {"label": "Dawnbird Remnant", "aodp_id_fragment": "ARTEFACT_2H_SHAPESHIFTER_AVALON"},
            {"label": "Shattered Avalonian Memento", "aodp_id_fragment": "ARTEFACT_OFF_TALISMAN_AVALON"},
            {"label": "Augured Padding", "aodp_id_fragment": "ARTEFACT_HEAD_LEATHER_AVALON"},
            {"label": "Augured Sash", "aodp_id_fragment": "ARTEFACT_ARMOR_LEATHER_AVALON"},
            {"label": "Augured Fasteners", "aodp_id_fragment": "ARTEFACT_SHOES_LEATHER_AVALON"},
            {"label": "Remnants of the Old King", "aodp_id_fragment": "ARTEFACT_2H_CLAYMORE_AVALON"},
            {"label": "Avalonian Battle Memoir", "aodp_id_fragment": "ARTEFACT_2H_AXE_AVALON"},
            {"label": "Broken Oaths", "aodp_id_fragment": "ARTEFACT_2H_DUALMACE_AVALON"},
            {"label": "Massive Metallic Hand", "aodp_id_fragment": "ARTEFACT_2H_HAMMER_AVALON"},
            {"label": "Damaged Avalonian Gauntlet", "aodp_id_fragment": "ARTEFACT_2H_KNUCKLES_AVALON"},
            {"label": "Humming Avalonian Whirligig", "aodp_id_fragment": "ARTEFACT_2H_CROSSBOW_CANNON_AVALON"},
            {"label": "Crushed Avalonian Heirloom", "aodp_id_fragment": "ARTEFACT_OFF_SHIELD_AVALON"},
            {"label": "Exalted Visor", "aodp_id_fragment": "ARTEFACT_HEAD_PLATE_AVALON"},
            {"label": "Exalted Plating", "aodp_id_fragment": "ARTEFACT_ARMOR_PLATE_AVALON"},
            {"label": "Exalted Greave", "aodp_id_fragment": "ARTEFACT_SHOES_PLATE_AVALON"},
        ),
    },
)

ARTIFACT_SALVAGE_FAMILIES_BY_KEY = {
    family["key"]: family for family in ARTIFACT_SALVAGE_FAMILIES
}

ARTIFACT_SALVAGE_ARTIFACTS_BY_AODP_FRAGMENT = {
    artifact["aodp_id_fragment"]: artifact
    for family in ARTIFACT_SALVAGE_FAMILIES
    for artifact in family["artifacts"]
}

ARTIFACT_SALVAGE_ARTIFACTS_BY_LABEL = {
    artifact["label"]: artifact
    for family in ARTIFACT_SALVAGE_FAMILIES
    for artifact in family["artifacts"]
}
