# Generated by Django 4.2.20 on 2025-07-14 15:37

from django.db import migrations, models

import runeterra.constants.region


class Migration(migrations.Migration):

    dependencies = [
        ("runeterra", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="champion",
            old_name="region",
            new_name="primary_region",
        ),
        migrations.AddField(
            model_name="champion",
            name="secondary_region",
            field=models.CharField(
                max_length=20,
                choices=runeterra.constants.region.Region.choices,
                blank=True,
                null=True,
            ),
        ),
    ]
