# Generated by Django 4.2.20 on 2025-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runeterra', '0002_add_secondary_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='primary_region',
            field=models.CharField(choices=[('TARGON', 'Targon'), ('RUNETERRA', 'Runeterra'), ('DEMACIA', 'Demacia'), ('NOXUS', 'Noxus'), ('IONIA', 'Ionia'), ('BANDLE', 'Bandle'), ('PILTOVER_ZAUN', 'Piltover & Zaun'), ('BILGEWATER', 'Bilgewater')], max_length=20),
        ),
    ]
