# Generated by Django 4.2.20 on 2025-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runeterra', '0003_alter_champion_primary_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='primary_region',
            field=models.CharField(choices=[('BANDLE', 'Bandle'), ('BILGEWATER', 'Bilgewater'), ('DEMACIA', 'Demacia'), ('FRELJORD', 'Freljord'), ('IONIA', 'Ionia'), ('NOXUS', 'Noxus'), ('PILTOVER_ZAUN', 'Piltover & Zaun'), ('RUNETERRA', 'Runeterra'), ('SHADOW_ISLES', 'Shadow Isles'), ('TARGON', 'Targon')], max_length=20),
        ),
    ]
