# Generated by Django 4.2.20 on 2025-07-20 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runeterra', '0004_alter_champion_primary_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champion_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='champion',
            name='star_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
