# Generated by Django 4.2.20 on 2025-08-21 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runeterra", "0007_alter_champion_primary_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="champion",
            name="star_level",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
