# Generated by Django 4.2.20 on 2025-08-21 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runeterra", "0008_alter_champion_star_level_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="monthly_try_remaining",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
